### PR TITLE
New ebi acession

### PR DESCRIPTION
**Pull request by squirrelo**
Updates the FAQ for the new EBI accession.

### CODE REVIEW

**Comment by squirrelo** [comment]
Can this get a quick review/merge?

**Comment by josenavas** [comment]
:+1: @EmbrietteH @ackermag can you verify that there is no issue with the new wording in here? Thanks

**Comment by squirrelo** [comment]
Was a direct copy paste from the word document so it shouldn't be, but good to have a double check.

**Comment by EmbrietteH** [comment]
Looks good to me.

**Pull request merged**
