### PR TITLE
Add constraints to barcode-related tables

### PR DESCRIPTION
**Pull request by adamrp**
Discussed in calls and emails with @wasade and @squirrelo. These tables should have constraints. I also reorganized the layout in the DBS file so that the relationships between these tables is easier to see visually.

The test code had to be modified to comply with the new constraints.

### CODE REVIEW

**Comment by wasade** [comment]
:+1: just realized, I don't actually know what barcode_exceptions is for, do you know?

**Comment by adamrp** [comment]
No, I don't, actually.... there are 525 barcodes in the table, all between
9k and 10k. The string "barcode_exceptions" does not appear to be  anywhere
in this codebase nor in the labadmin codebase. Hmmmmm

**Comment by wasade** [comment]
Likely another carry over?

**Comment by adamrp** [comment]
Sorry to say I have no idea :confused:

**Comment by adamrp** [comment]
If we want, I can drop the table, but of course I don't know what unforeseen consequences doing so might have. Or we can drop it at a later date, and go ahead with this PR as is.

**Comment by squirrelo** [comment]
I'm good with leaving it and checking later.

**Comment by wasade** [comment]
sounds good. @squirrelo, okay with merge?

**Comment by adamrp** [comment]
Note that merge request 18 on glab needs to be merged before this is deployed, or the make_kits_and_insert script won't work.

**Pull request merged**
