### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by adamrp**
Has initial instructions about database patches

### CODE REVIEW

**Comment by antgonza** [comment]
@adamrp ping!

**Comment by wasade** [comment]
@adamrp, ping on this

**Comment by adamrp** [comment]
We never implemented a patching system in american-gut-web, and the only thing that my contribution to CONTRIBUTING.md was intended to cover was the patching system, so I think this PR can be closed.

There should be a CONTRIBUTING.md file, however, so I created #364

**Comment by adamrp** [comment]
Woops -- I was looking at an old version of the repo. We do have patches -- thanks @wasade

**Comment by squirrelo** [comment]
:+1:

**Pull request merged**
