### PR TITLE
Use zipcodes table instead of info in ag_login

### PR DESCRIPTION
**Pull request by adamrp**
This will address parts of #410

### CODE REVIEW

**Comment by adamrp** [comment]
dont merge yet, still tinkering

**Comment by adamrp** [comment]
okay, ready for final review and merge

**Comment by wasade** [comment]
Is this going to impact inserts into ag_login?

Should zipcode be varchar? US ones can include a dash, are prefixed by
zeros (eg CT) and the field is used for postal codes in other countries
where the code is not assured to be numeric

**Comment by adamrp** [comment]
> Is this going to impact inserts into ag_login?

Good point. Things may have to be modified there...

> Should zipcode be varchar? US ones can include a dash, are prefixed by
zeros (eg CT) and the field is used for postal codes in other countries
where the code is not assured to be numeric

The zipcode column in the zipcodes table is a varchar, or am I mistaken?

**Comment by wasade** [comment]
ah, sorry, looked incorrectly when reading on my phone

**Pull request merged**
