### PR TITLE
Delete sample bug

### PR DESCRIPTION
**Pull request by antgonza**
This should pass all tests.

### CODE REVIEW

**Comment by wasade** [comment]
I'm :+1: but I'm biased :) 

@josenavas @mortonjt @ElDeveloper possible for review? PR is short, and addresses a bug in production. 

cc @EmbrietteH

**Comment by mortonjt** [comment]
At a first glance, this looks ok.

But I guess I'm a little confused about what is going on.  It seems like the function signature for `deleteSamples` was initially accepting an `ag_login_id`.  Was the `deleteAGParticipantSurvey` always broken?  If so, 👍 for resolving this.

**Comment by wasade** [comment]
yes

**Comment by mortonjt** [comment]
Ok.  Then if there is no objections, I can merge this.

**Comment by wasade** [comment]
that'd be great, thanks!!

**Comment by mortonjt** [comment]
Thanks @antgonza !

**Pull request merged**
