### PR TITLE
Add new questions to survey

### PR DESCRIPTION
**Pull request by squirrelo**
This adds the two new questions from the IRB amendment to the main AG survey.

### CODE REVIEW

**Comment by josenavas** [comment]
@EmbrietteH @ackermag can you double-check that the wording in here is as expected?

👍 otherwise

**Comment by EmbrietteH** [comment]
👍

**Comment by EmbrietteH** [comment]
@ackermag I didn't see any typos but will you please double check?

**Comment by ackermag** [comment]
Can we check tomorrow?
Gail

On Thu, Jun 9, 2016 at 2:06 PM, Embriette Hyde <notifications@github.com>
wrote:

> @ackermag <https://github.com/ackermag> I didn't see any typos but will
> you please double check?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/american-gut-web/pull/590#issuecomment-225026644>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB69gG-V9eEeyYHMwKtgJSiP6gA90Qmkks5qKIBPgaJpZM4IqxtY>
> .
>



-- 
Gail Ackermann
Knight Lab
UCSD
glackermann@ucsd.edu <ackermag@ucsd.edu>

**Comment by josenavas** [comment]
@ackermag did you had a chance to check this? I would like to have your eyes over this to make sure that it matches IRB and that we are not missing any question.

**Pull request merged**
