### PR TITLE
Fixed BG FAQ listing wrong address

### LINKED ISSUE #687: Boulder address is listed in BG site
In the FAQ

### PR DESCRIPTION
**Pull request by AlexanderFengFeng**
Fixes #687

### CODE REVIEW

**Comment by wasade** [comment]
@AlexanderFengFeng, it looks like you need to merge from `master` as this PR includes commits from #693 which was already merged.

@ElDeveloper, would it be possible to sit with @AlexanderFengFeng today for a moment and show Alexander how to do this?

**Comment by AlexanderFengFeng** [comment]
I'll be coming in at 1:30ish I need to meet my mother right now.

**Comment by ElDeveloper** [comment]
Unfortunately, I won't be in today.

**Comment by wasade** [comment]
Great!

**Pull request merged**
