### PR TITLE
Plate mapper db changes

### PR DESCRIPTION
**Pull request by squirrelo**
This adds in the tables and database modifications needed for a full sample tracking and prep information storage and retrieval.

This needs to be in AG because all DB patching is done through AG. All subsequent code PRs will be in labadmin.

### CODE REVIEW

**Comment by squirrelo** [comment]
Ready for review. Incorporates the few comments I got on the original pull request.

**Comment by mortonjt** [comment]
First pass through.  I don't see any obvious problems.

However, given that there is a ton of changes to the database, I would recommend against merging this without any additional unit-tests.

**Comment by squirrelo** [comment]
There is no way to unit test any of this, as it has no data and the structures using it still have not been added to labamin.

**Comment by squirrelo** [comment]
Had some discussions and made a few more changes, this should now be the final version and ready to merge.

**Comment by mortonjt** [comment]
Sounds good

**Pull request merged**
