### PR TITLE
Add participant agreement wording

### PR DESCRIPTION
**Pull request by squirrelo**
This adds the new participant agreement wording.

### CODE REVIEW

**Comment by squirrelo** [comment]
Ready for review.

**Comment by mortonjt** [comment]
Thank you for putting this together!

**Comment by mortonjt** [comment]
Just tested out all of the functionality.  Seems to be working.  I'll merge it right after @EmbrietteH reviews the consent.

**Comment by mortonjt** [comment]
@ackermag just ok'ed the consent form.  Merging ...

**Pull request merged**
