### PR TITLE
Add missing birth years

### LINKED ISSUE #639: survey does not include birth year of 2016/2017
Participants entering their children (born in 2016/2017) do not have those years as options in the dropdown on the personal info survey

### PR DESCRIPTION
**Pull request by wasade**
Fixes #639

### CODE REVIEW

**Comment by EmbrietteH** [comment]
👍

**Comment by sjanssen2** [comment]
Wow, do we have to do those types of patches every year?
How can we make sure one of us actually does this update every January?

**Comment by rob-knight** [comment]
Populating it dynamically based on curr date might be better idea...?

On Mar 7, 2017, at 12:55 PM, Stefan Janssen <notifications@github.com<mailto:notifications@github.com>> wrote:


Wow, do we have to do those types of patches every year?
How can we make sure one of us actually does this update every January?

-

**Comment by sjanssen2** [comment]
Or populate for the next 100 years but only display up to the current year in the survey / website.

**Pull request merged**
