### PR TITLE
Add text to interactive pages

### PR DESCRIPTION
**Pull request by squirrelo**
This adds all text into the page, as well as making it translation-friendly. It also tweaks a few file names to work with the American-Gut repo generated files.

screencapture-localhost-8888-authed-multiple-1462817845518

### CODE REVIEW

**Comment by squirrelo** [comment]
ping @EmbrietteH @wasade

**Comment by EmbrietteH** [comment]
Do you have screenshots of how the text renders on the page?

**Comment by squirrelo** [comment]
Added to the initial comment

**Comment by EmbrietteH** [comment]
Looks good, once @wasade is ok with changes to maintain continuity with repo-gen files will be good to merge.

**Pull request merged**
