### PR TITLE
Issue 485 - Test database ownership and reset

### PR DESCRIPTION
**Pull request by squirrelo**
This changes the test database to not set ownership or users itself, and instead breaks build and initialize into two functions so the ownership can be set for the test database.

This also sets ownership of all databases during the make command to the owner in the settings file, instead of ag_wwwuser always.

Finally, this changes the functions around to allow reset of the test database. calling `ag rebuild-test-db` will check if the database is a test database, and if so drop the database and rebuild it.

### CODE REVIEW

**Comment by squirrelo** [comment]
@beaugunderson this should fix the issue you had.

**Comment by beaugunderson** [comment]
@squirrello excellent, will test this out momentarily!

**Comment by beaugunderson** [comment]
@squirrelo OK, `./scripts/ag make test` worked flawlessly with this PR:

```sh
$ ./scripts/ag make test
Creating database
Populating the test database
Granting privileges
Applying patches to database
test environment successfully created
```

but starting the server errors immediately:

```sh
$ ./amgut/webserver.py --port=8081
Traceback (most recent call last):
  File "./amgut/webserver.py", line 25, in <module>
    from amgut.handlers.animal_survey import (AnimalSurveyHandler,
  File "/Users/beau/p/american-gut-web/amgut/handlers/animal_survey.py", line 11, in <module>
    from amgut.lib.survey_supp import primary_animal_survey
  File "/Users/beau/p/american-gut-web/amgut/lib/survey_supp.py", line 3, in <module>
    primary_human_survey = Survey(1)
  File "/Users/beau/p/american-gut-web/amgut/lib/data_access/survey.py", line 272, in __init__
    [self.id])]
  File "/Users/beau/p/american-gut-web/amgut/lib/data_access/survey.py", line 213, in __init__
    [self.id])]
  File "/Users/beau/p/american-gut-web/amgut/lib/data_access/sql_connection.py", line 144, in execute_fetchall
    with self._sql_executor(sql, sql_args) as pgcursor:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/beau/p/american-gut-web/amgut/lib/data_access/sql_connection.py", line 122, in _sql_executor
    "\nError: %s" % (err_sql, e)))
ValueError:
Error running SQL query:
            SELECT gq.survey_question_id
            FROM survey_group sg
            JOIN group_questions gq ON sg.group_order = gq.survey_group
            LEFT JOIN survey_question sq USING (survey_question_id)
            WHERE sg.group_order =  -1 AND sq.retired = FALSE
            ORDER BY gq.display_index

Error: column sq.retired does not exist
LINE 6:             WHERE sg.group_order =  -1 AND sq.retired = FALS...
```

**Comment by squirrelo** [comment]
Hmmm, could you check the settings table and see what patch the database is on?

**Comment by beaugunderson** [comment]
It looks like "23" is baked into the `ag_test_patch22.sql` file; and because of that my settings table says "23".

**Comment by squirrelo** [comment]
Let me take a look, should have a fix momentarily.

**Comment by beaugunderson** [comment]
Also noting that if I set it to "0022.sql" and run patch I fail with this:

```
psycopg2.ProgrammingError: syntax error at or near "INSERT"
LINE 67: INSERT INTO ag.survey_answers (survey_id, survey_question_id...
```

**Comment by squirrelo** [comment]
Everything should be good now and works on my computer, but please double check.

**Comment by beaugunderson** [comment]
:+1:!

One more question though--it looks like all the test kits use the same password in the test database, what is it?

**Comment by squirrelo** [comment]
The test password is `test`

**Comment by beaugunderson** [comment]
Ah, excellent. :)

**Comment by beaugunderson** [comment]
Hm, logging in as `tst_ycGwb` with password `test` fails. Should I make a new issue for this?

**Comment by squirrelo** [comment]
The kit IDs are regenerated randomly each time the database is scrubbed, so that supplied kit ID no longer exists. try `tst_DXXov`.

**Comment by beaugunderson** [comment]
confirming that `tst_DXXov` did work, thanks. :)

**Comment by beaugunderson** [comment]
Will `reset_test_database` in `amgut/lib/util.py` need the split build/initialize as well?

**Comment by squirrelo** [comment]
It is getting removed in this pull request in favor of other test resets.

**Pull request merged**
