### PR TITLE
fix Open Humans issue by base64 encoding cookie

### PR DESCRIPTION
**Pull request by beaugunderson**
...to workaround [this bug in Python pre-2.7.10](https://bugs.python.org/issue22931).

### CODE REVIEW

**Comment by beaugunderson** [comment]
@squirrelo possible to merge this? :)

**Comment by squirrelo** [comment]
Yup, done :D

**Comment by beaugunderson** [comment]
thanks @squirrelo! any idea when it will be deployed?

**Comment by squirrelo** [comment]
tonight most likely

**Comment by beaugunderson** [comment]
@squirrelo noticed this didn't get deployed; any chance of it getting deployed before holidays start tomorrow? we are super excited to email people before then if possible :)

**Comment by squirrelo** [comment]
sorry, another problem came up. Deploying now.

**Comment by squirrelo** [comment]
Deploy out :)

**Comment by beaugunderson** [comment]
thanks @squirrelo, everything looks good! :sparkles:

**Pull request merged**
