### PR TITLE
WIP - Plate mapper DB

### PR DESCRIPTION
**Pull request by squirrelo**
This is the inital design for the plate mapper and how data will be stored. Please take a close, close look at this and ask as many questions as needed. The design should be extensible enough to cover not just what we currently do in the lab, but anything from metabolomics to WGS and onwards. 

Due to the complexity and importance of this PR, I'd like to get at least 3 people to review it, if not more. This is currently for design decisions. Once we agree on the design, I will generate the SQL using DBSchema and add it to this PR.

### CODE REVIEW

**Comment by squirrelo** [comment]
ping @biocore/american-gut-admin @biocore/american-gut-web-admin

**Comment by wasade** [comment]
Why is this in AG web and not labadmin?

**Comment by squirrelo** [comment]
DB changes need to happen in AG since we can't patch from labadmin. All subsequent things will be in labadmin.

**Comment by squirrelo** [comment]
No comments, so closing to make final PR

**Pull request closed without merging**
