### PR TITLE
More log samples messages

### PR DESCRIPTION
**Pull request by squirrelo**
This adds a bold, red message to the top of each portal tab stating there are samples that were received but do not have consent. It also adds a reminder at the end of the survey that you need to associate a sample in order to get it processed.

### CODE REVIEW

**Comment by squirrelo** [comment]
Here is the message in context: 
screen shot 2016-01-12 at 16 38 33

**Comment by EmbrietteH** [comment]
Really minor point: can not = cannot
Also, would it be appropriate to perhaps add a short phrase like: "A list of non-associated barcodes appears below"?
ping @mortonjt @JWDebelius for a second set of eyes

**Comment by mortonjt** [comment]
The rendering looks good. I think it is good to go once @EmbrietteH 's comment is addressed

**Comment by squirrelo** [comment]
Change made, ready to go.

**Pull request merged**
