### PR TITLE
BUG: added sitebase to taxa summary link

### PR DESCRIPTION
**Pull request by wasade**
@squirrelo @adamrp @ElDeveloper, possible for quick review please? This is a bug that impacts production

### CODE REVIEW

**Comment by squirrelo** [comment]
:+1:

**Comment by adamrp** [comment]
Code looks good, going to test now

**Comment by adamrp** [comment]
After changing to new computer this weekend, I am having to get my environment set up again, and am having some install difficulties (libffi). I'm going to keep working through those issues so that my development environment works again. However, if someone with a currently working dev environment can get to this sooner, that would probably best for prompt merging/deployment of this fix.

**Comment by adamrp** [comment]
Okay, this works! merging

**Comment by wasade** [comment]
Thanks!

**Pull request merged**
